databases:
  - name: Kpopedia_DB
    databaseName: Kpopedia_db
    user: Kpopedia
    region: singapore

services:
  - type: web
    name: Kpopedia
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Kpopedia_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

